version: "3"
services:
    ricky:
        image: mchangrh/ricky:latest
        container_name: ricky
        volumes:
            - type: volumes
              source: ricky-stores
              target: /usr/src/ricky/stores
            - type: bind
              source: ./secrets.json
              target: /usr/src/ricky/config/secrets.json
            - type: bind
              source: ./ricky-sa.json
              target: /usr/src/ricky/config/ricky-sa.json

volumes:
    ricky-stores: